apiVersion: apps/v1
kind: Deployment
metadata:
  name: immo-mcp-server
  namespace: g2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immo-mcp
  template:
    metadata:
      labels:
        app: immo-mcp
    spec:
      containers:
      - name: immo-mcp
        image: ghcr.io/solenhya/immo-mcp:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: immo-env
      imagePullSecrets:
      - name: ghcr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: immo-mcp-service
  namespace: g2
spec:
  selector:
    app: immo-mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
